# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ed9fe53d894402536e8434645e30b1899e059184aba819d0c0d34cee5434dc01ab3c74be0fab9b5889c046674a19e005a816fa5ffebae356cef91f67b92b4cc

test:
  secret_key_base: 379672109d1dc6a646bc8dd3e5c6ab01209fadb3badd7e3a5f309ec3a2c48c6caa0c23f68ef81792ddc8204547098c0aacadc59681b5aab8c5208198900ce065

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
